package be.gentsefeesten.interfaces

interface EventTabel {
    companion object {
        const val TABEL_NAAM = "tblEvents"
        const val OFFER_AVAILABLEATFORFROM = "_event_offer_availableatforfrom"
        const val SUPEREVENT = "_event_superevent"
        const val KEYWORDS = "_event_keywords"
        const val LOCATION = "_event_location"
        const val OFFERS_NEW = "_event_offers_new"
        const val URL = "_event_url"
        const val ID = "_event_id"
        const val TYPE = "_event_type"
        const val IMAGE = "_event_image"
        const val ISACCESSIBLEFORFREE = "_event_isaccessibleforfree"
        const val OFFER_PRICECURRENCY = "_event_offer_pricecurrency"
        const val ORGANIZER = "_event_organizer"
        const val NAME = "_event_name"
        const val IMAGE_THUMBNAIL = "_event_image_thumbnail"
        const val OFFER_DESCRIPTION = "_event_offer_description"
        const val CONTACTPOINT = "_event_contactpoint"
        const val CREATED = "_event_created"
        const val THEME = "_event_thme"
        const val IMAGE_CAPTION = "_event_image_caption"
        const val DESCRIPTION_NL = "_event_description_nl"
        const val UUID = "_event_uuid"
        const val ENDDATE = "_event_enddate"
        const val DESCRIPTION = "_event_description"
        const val ADDRESS = "_event_address"
        const val ISPARTOF = "_event_ispartof"
        const val NAME_NL = "_event_name_nl"
        const val OUTDOORS = "_event_outdoors"
        const val IMAGE_PATH = "_event_image_path"
        const val OFFERS = "_event_offers"
        const val STARTDATE = "_event_startdate"
        const val CHANGED = "_event_changed"
        const val ISWHEELCHAIRUNFRIENDLY = "_event_iswheelchairunfriendly"
    }
}